name: Converts comments to input configuration

steps:
  - ref: ./background.toolproof.yml
  - step: I have a "component-lib/components/test/test.bookshop.toml" file with the content {toml}
    toml: |-
      [props]
      text.default = "Hello World" #: CMS Comment

      [[props.array]] #: Array Comment
      array_text.default = "Hi Globe" #: Text Comment
  - step: I run "npm start -- --yes --version 3.0.0 --format yml --skip-commands"
  - step: stderr should be empty
  - step: stdout should contain "🌟 component-lib/components/test/test.bookshop.toml @ 2.0 → yml @ 3.0"
  - snapshot: The file "component-lib/components/test/test.bookshop.yml"
    snapshot_content: |-
      ╎# Metadata about this component, to be used in the CMS
      ╎spec: {}
      ╎
      ╎# Defines the structure of this component, as well as the default values
      ╎blueprint:
      ╎  text: Hello World
      ╎  array:
      ╎    - array_text: Hi Globe
      ╎
      ╎# Overrides any fields in the blueprint when viewing this component in the component browser
      ╎preview: {}
      ╎
      ╎# Any extra CloudCannon inputs configuration to apply to the blueprint
      ╎_inputs:
      ╎  text:
      ╎    comment: CMS Comment
      ╎  array:
      ╎    comment: Array Comment
      ╎  array_text:
      ╎    comment: Text Comment
