name: Converts non-default values

steps:
  - ref: ./background.toolproof.yml
  - step: I have a "component-lib/components/test/test.bookshop.toml" file with the content {toml}
    toml: |-
      [props]
      text = "Hello World"
  - step: I run "npm start -- --yes --version 3.0.0 --format yml --skip-commands"
  - step: stderr should be empty
  - step: stdout should contain "🌟 component-lib/components/test/test.bookshop.toml @ 2.0 → yml @ 3.0"
  - snapshot: The file "component-lib/components/test/test.bookshop.yml"
    snapshot_content: |-
      ╎# Metadata about this component, to be used in the CMS
      ╎spec: {}
      ╎
      ╎# Defines the structure of this component, as well as the default values
      ╎blueprint:
      ╎  text: ""
      ╎
      ╎# Overrides any fields in the blueprint when viewing this component in the component browser
      ╎preview:
      ╎  text: Hello World
      ╎
      ╎# Any extra CloudCannon inputs configuration to apply to the blueprint
      ╎_inputs: {}
  - step: I run "npm start -- --yes --version 3.0.0 --format js --skip-commands"
  - step: stderr should be empty
  - step: stdout should contain "🌟 component-lib/components/test/test.bookshop.yml @ 3.0 → js @ 3.0"
  - snapshot: The file "component-lib/components/test/test.bookshop.js"
    snapshot_content: |-
      ╎module.exports = () => {
      ╎  // Metadata about this component, to be used in the CMS
      ╎  const spec = {};
      ╎
      ╎  // Defines the structure of this component, as well as the default values
      ╎  const blueprint = { text: '' };
      ╎
      ╎  // Overrides any fields in the blueprint when viewing this component in the component browser
      ╎  const preview = { text: 'Hello World' };
      ╎
      ╎  // Any extra CloudCannon inputs configuration to apply to the blueprint
      ╎  const _inputs = {};
      ╎
      ╎  return {
      ╎    spec,
      ╎    blueprint,
      ╎    preview,
      ╎    _inputs,
      ╎  }
      ╎}
  - step: I run "npm start -- --yes --version 3.0.0 --format json --skip-commands"
  - step: stderr should be empty
  - step: stdout should contain "🌟 component-lib/components/test/test.bookshop.js @ 3.0 → json @ 3.0"
  - snapshot: The file "component-lib/components/test/test.bookshop.json"
    snapshot_content: |-
      ╎{
      ╎  "spec": {},
      ╎  "blueprint": {
      ╎    "text": ""
      ╎  },
      ╎  "preview": {
      ╎    "text": "Hello World"
      ╎  },
      ╎  "_inputs": {}
      ╎}
