name: Creates config for nested objects

steps:
  - ref: ./background.toolproof.yml
  - step: I have a "component-lib/components/test/test.bookshop.toml" file with the content {toml}
    toml: |-
      [props]
      title.default = "My Component"

      [[props.tags]]
      tag_type.select = ["Major", "Minor"] #: Used in the changelog
      tag = "Bookshop"

      [[props.tags]]
      tag_type.select = ["Major", "Minor"]
      tag = "Component"
  - step: I run "npm start -- --yes --version 3.0.0 --format js --skip-commands"
  - step: stderr should be empty
  - step: stdout should contain "🌟 component-lib/components/test/test.bookshop.toml @ 2.0 → js @ 3.0"
  - snapshot: The file "component-lib/components/test/test.bookshop.js"
    snapshot_content: |-
      ╎module.exports = () => {
      ╎  // Metadata about this component, to be used in the CMS
      ╎  const spec = {};
      ╎
      ╎  // Defines the structure of this component, as well as the default values
      ╎  const blueprint = {
      ╎    title: 'My Component',
      ╎    tags: [
      ╎      { tag_type: 'Major', tag: '' }
      ╎    ]
      ╎  };
      ╎
      ╎  // Overrides any fields in the blueprint when viewing this component in the component browser
      ╎  const preview = { tags: [ { tag: 'Bookshop' }, { tag: 'Component' } ] };
      ╎
      ╎  // Any extra CloudCannon inputs configuration to apply to the blueprint
      ╎  const _inputs = {
      ╎    tag_type: {
      ╎      comment: 'Used in the changelog',
      ╎      type: 'select',
      ╎      options: {
      ╎        values: [
      ╎          'Major',
      ╎          'Minor'
      ╎        ]
      ╎      }
      ╎    }
      ╎  };
      ╎
      ╎  return {
      ╎    spec,
      ╎    blueprint,
      ╎    preview,
      ╎    _inputs,
      ╎  }
      ╎}
