source "https://rubygems.org"

gem "jekyll", "~> 4.1.1"

group :jekyll_plugins do
    gem 'jekyll-watch', :git => "https://github.com/CloudCannon/jekyll-watch"
    #gem 'jekyll-watch', :path => "../../../CC/jekyll-watch"
end