= Bookshop Editor Links
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toc:
:toc-placement!:

toc::[]

[.lead]
When live editing a page in CloudCannon Bookshop will automatically generate link:https://cloudcannon.com/documentation/articles/extending-in-app-navigation-with-editor-links/[Editor Links]. These highlight components on the page, and open a floating editor panel scoped to the front matter data for that component.

== Configuration

Editor Links are only rendered when using Bookshop link:live-editing.adoc[Live Editing], so following those integration steps are the primary requirement.

== Customization

Bookshop adds Editor Links for any component that renders using front matter from the page. For most use cases these links will work as expected, and they work especially well when combined with CloudCannon Structures and page building.

By default, Bookshop will add Editor Links for any components on the page, but will not add Editor Links for shared includes/partials. For example, in Eleventy:

.*index.html*
```
<!-- This component will get an automatic Editor Link -->
{% bookshop 'item' props: props %}

<!-- This include will not get an Editor Link added by default -->
{% bookshop_include 'page' props: props %}
```

This allows you to create, for example, a page include that renders your components in a loop, without an editor link being added for the page as a whole. Each component within will still get an editor link generated.

The behavior of each scenario can be customised by including a flag in the component's props. Bookshop will look for any of the following attributes:

* editor_link
* editorLink
* _editor_link
* _editorLink

So for example, in Eleventy:

.*index.html*
```
<!-- This component will **not** get an Editor Link -->
{% bookshop 'item' editor_link: false, props: props %}

<!-- This include will get an Editor Link -->
{% bookshop_include 'page' editor_link: true, props: props %}
```

NOTE: This flag only applies to the component directly and doesn't cascade down. Any subcomponents will follow the standard rules, or can also specify their own Editor Link flag.

If you have a specific component that you never want an Editor Link applied to, you can set `_editor_link` in the component props. 

.*component.bookshop.toml*
```
[component]
...

[props]
_editor_link: false
...
```

This will be hidden from editors due to the leading underscore, and will disable Editor Links for that component anywhere it is rendered.

== Disabling

This behavior is enabled by default. If you want to opt out entirely and set Editor Links manually, you can set `window.bookshopEditorLinks = false` anywhere in your page's javascript.
