= Bookshop Live Editing
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toc:
:toc-placement!:

toc::[]

[.lead]
Bookshop provides the ability for your editors to preview changes live while editing your page in CloudCannon.

IMPORTANT: This is an experimental feature

== Configuration

Live editing relies on the Bookshop Live package.

To install this as a development dependency, run: +
`npm i -D @bookshop/live`

== Building the live editing scrips

Before your CloudCannon build, run: +
`npx bookshop-live -b ./path/to/components -o site/assets/bookshop-live.js`

[cols="2", options="header"]
|===
|Flag
|Purpose

|-b, --bookshop
|Bookshop directories to build for live editing

|-o, --output
|File path to save the javascript file to
|===

This is best used in an npm script, eg:
```json
{
    "scripts": {
        "start": "bookshop-live -b ./path/to/components -o site/assets/bookshop-live.js"
    }
}
```

Paired with a CloudCannon prebuild script:
.*.cloudcannon/prebuild*
```bash
npm install
npm run bookshop-live
```

TIP: You can supply the `-b` flag multiple times if you want to merge Bookshops.

== Integration

The Bookshop generator frameworks provide helpers for integrating live editing with your website.

Within Jekyll, the *cloudcannon-jekyll-bookshop* plugin provides a `bookshop_live` tag to embed the browser on a given page. Within Eleventy, this tag is supplied by the *@bookshop/cloudcannon-eleventy-bookshop* plugin. +
See the link:jekyll.adoc[Jekyll] 
or link:eleventy.adoc[Eleventy] 
guides for instructions on installing these plugins.

The syntax is the same across both generators:

.*_layouts/default.html*
```liquid
    ...
    {% bookshop_live site/assets/bookshop-live.js %}
</body>
```

Ideally this is placed in your default layout to enable live editing across all pages.

NOTE: Make sure the path of the JavaScript file matches the `-o` flag of the `bookshop-live` command earlier.

With the plugins installed and the `bookshop_live` tag integrated in your site layout, live editing should now be working for your pages on CloudCannon. This will only work within Bookshop components and includes, not your site as a whole.

As a result, it is recommended to render groups of Bookshop components using a `page` Bookshop include. See the implementation in the link:https://github.com/CloudCannon/eleventy-bookshop-starter[Eleventy Bookshop Starter] for an example.
