source "https://rubygems.org"
gem "jekyll", "~> 4.2.0"

group :jekyll_plugins do
  gem 'cloudcannon-jekyll', "~> 3"
  gem "jekyll-bookshop", :path => "../../../generator-plugins/jekyll/jekyll-bookshop"
end
