#!/bin/sh

CHANGES=$(git diff --cached --name-only) 
CHANGED_GUIDE=$(echo $CHANGES | grep -c "guides/")

if [ $CHANGED_GUIDE != "0" ]; then
    if [[
           -z $(echo $CHANGES | grep "hugo.adoc")
        || -z $(echo $CHANGES | grep "eleventy.adoc")
        || -z $(echo $CHANGES | grep "jekyll.adoc")
    ]]; then
        echo "One of the SSG guides was changed without updating the others."
        echo "Run ./scripts/build-guides.sh before comitting."
        exit 1
    fi
fi
