[module]
hugoVersion.extended = true
hugoVersion.min = "0.86.1"

[[module.mounts]]
source = "core"
target = "layouts/partials/_bookshop"

[[module.mounts]]
source = "core/bookshop.html"
target = "layouts/partials/bookshop.html"

[[module.mounts]]
source = "core/bookshop_scss.html"
target = "layouts/partials/bookshop_scss.html"
