# Starter Gemfile
source "https://rubygems.org"
gem "jekyll", "~> 4.1.1"

group :jekyll_plugins do
    gem "jekyll-bookshop", :path => "../../../../generator-plugins/jekyll/jekyll-bookshop"
    gem "cloudcannon-jekyll-bookshop", :path => "../../../../generator-plugins/jekyll/cloudcannon-jekyll-bookshop"
end