[module]
hugoVersion.extended = true
hugoVersion.min = "0.86.1"

[[module.imports]]
path = 'github.com/cloudcannon/bookshop/hugo/v2'

[[module.mounts]]
source = "components"
target = "layouts/partials/bookshop"

[[module.mounts]]
source = "shared/hugo"
target = "layouts/partials/bookshop-partials"
