[module]
hugoVersion.extended = true
hugoVersion.min = "0.86.1"

[[module.imports]]
path = 'github.com/cloudcannon/bookshop/hugo/v2'

[[module.mounts]]
source = "."
target = "layouts/partials/bookshop"

[[module.mounts]]
source = "."
target = "assets/bookshop"
