[module]
hugoVersion.extended = true
hugoVersion.min = "0.86.1"

[[module.imports]]
path = 'github.com/cloudcannon/hugo-bookshop'

[[module.mounts]]
source = "components"
target = "layouts/partials/bookshop"

[[module.mounts]]
source = "shared/hugo"
target = "layouts/partials/bookshop-include"
