name: Javascript

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  node-test:
    runs-on: ${{ matrix.os }}

    env:
      cwd: ./javascript-modules

    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --immutable
        working-directory: ${{ env.cwd }}
      - run: yarn workspaces foreach run test
        working-directory: ${{ env.cwd }}
      # - name: Run tests without hoisted packages
      #   run: ./scripts/hoistless-test.js
